default: &default
  adapter: postgresql
  encoding: unicode
  username: elly
  password: immortal
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: article_app_development

test:
  <<: *default
  database: article_app_test

production:
  <<: *default
  database: article_app_production
  username: article_app
  password: <%= ENV['ARTICLE_APP_DATABASE_PASSWORD'] %>
